# These are supported funding model platforms

patreon: # https://www.patreon.com/user?u=19935929 (https://www.patreon.com/user?u=19935929)
paypal: # https://www.paypal.me/breadsplit/USD5 (https://www.paypal.me/breadsplit/USD5)
