# https://www.netlify.com/docs/netlify-toml-reference/

[build]
  base = ""
  publish = "packages/client/dist/"
  command = "npm run generate"

[build.environment]
  GOOGLE_GTAG_ID = "UA-139660905-1" # dev gtag
  RELEASE_CHANNEL = "dev"
  FIREBASE_SERVER = "development"
  SENTRY_DSN = "https://5decd6ec1a0e42d7b1f47d92675e0b59@sentry.io/1457153"


# "app" branch
[context.app.environment]
  GOOGLE_GTAG_ID = "UA-139660905-3" # prod gtag
  RELEASE_CHANNEL = "beta"
  FIREBASE_SERVER = "production"


# "website" branch
[context.website]
  base = ""
  publish = "packages/website/dist"
  command = "npm run web:generate"

[context.website.environment]
  GOOGLE_GTAG_ID = "UA-139660905-5" # website gtag


# "docs" branch
[context.docs]
  base = ""
  publish = "packages/docs/.vuepress/dist/"
  command = "npm run docs:build"

[context.docs.environment]
  GOOGLE_GTAG_ID = "UA-139660905-4" # docs gtag


# Redirects
[[redirects]]
  from = "https://breadsplit.netlify.com/*"
  to = "https://breadsplit.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = 'https://docs.breadsplit.com/*'
  to = '/:splat'
  status = 200
  force = true

[[redirects]]
  from = '/*'
  to = '/index.html'
  status = 200

