# https://www.netlify.com/docs/netlify-toml-reference/

[build]
  base = ""
  publish = "client/dist/"
  command = "npm run generate"

[build.environment]
  GOOGLE_GTAG_ID = "UA-139660905-1" # dev gtag
  RELEASE_CHANNEL = "dev"
  FIREBASE_SERVER = "development"
  SENTRY_DSN = "https://5decd6ec1a0e42d7b1f47d92675e0b59@sentry.io/1457153"

# App branch
[context.app.environment]
  GOOGLE_GTAG_ID = "UA-139660905-3" # prod gtag
  RELEASE_CHANNEL = "beta"
  FIREBASE_SERVER = "production"

# Website branch
[context.website]
  base = ""
  publish = "docs/.vuepress/dist/"
  command = "npm run docs:build"

[context.website.environment]
  GOOGLE_GTAG_ID = "UA-139660905-4"
