# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1

orbs:
  codecov: codecov/codecov@1.0.4
  cypress: cypress-io/cypress@1.7.0

jobs:
  unit_test:
    docker:
      - image: circleci/node:10

    working_directory: ~/app

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Install dependencies
          command: npm i

      - save_cache:
          paths:
            - node_modules

          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Run tests
          command: npm test

      - codecov/upload:
          file: ./src/coverage/*.json


workflows:
  version: 2
  build_and_test:
    jobs:
      - unit_test

      - cypress/run:
          record: true
          wait-on: 'http://localhost:3000'
          start: FIERBASE_SERVER=test npm run generate && npm run generate:host
