# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1

orbs:
  codecov: codecov/codecov@1.0.4
  cypress: cypress-io/cypress@1.7.0

jobs:
  unit_test:
    docker:
      - image: cypress/node:10

    steps:
      - checkout

      - restore_cache:
          keys:
            - cache-{{ arch }}-{{ .Branch }}-{{ checksum "package.json" }}

      - run:
          name: Npm CI
          command: npm ci

      - save_cache:
          key: cache-{{ arch }}-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ~/.npm
            - ~/.cache

      - run:
          name: Run tests
          command: npm test

      - codecov/upload:
          file: ./src/coverage/*.json


workflows:
  version: 2
  build_and_test:
    jobs:
      - cypress/install

      - unit_test:
          requires:
            - cypress/install

      - cypress/run:
          requires:
            - cypress/install
          record: true
          wait-on: 'http://localhost:3000'
          start: npm run generate && npm run generate:host
